[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:garage-init]
command=/server-init.sh
autostart=true
autorestart=false
startsecs=0
startretries=0
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:garage-webui]
command=/usr/local/bin/garage-webui
environment=CONFIG_PATH="/etc/garage.toml",API_BASE_URL="http://127.0.0.1:3903",S3_ENDPOINT_URL="http://127.0.0.1:3900",S3_REGION="garage",API_ADMIN_KEY="%(ENV_GARAGE_ADMIN_TOKEN)s",AUTH_USER_PASS="%(ENV_AUTH_USER_PASS)s",HOST="0.0.0.0",PORT="3909"
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true