#!/bin/sh
# POSIX entrypoint for Garage on Coolify
# Auto-generates /var/lib/garage/garage.toml from env vars, bootstraps cluster on first boot.

set -e

CONFIG="/var/lib/garage/garage.toml"
MARKER="/var/lib/garage/.initialized"

# ---------------------------------------------------------------------------
# 1. Defaults
# ---------------------------------------------------------------------------
GARAGE_RPC_BIND_ADDR="${GARAGE_RPC_BIND_ADDR:-0.0.0.0:3900}"
GARAGE_METADATA_DIR="${GARAGE_METADATA_DIR:-/var/lib/garage/meta}"
GARAGE_DATA_DIR="${GARAGE_DATA_DIR:-/var/lib/garage/data}"

GARAGE_S3_API_BIND_ADDR="${GARAGE_S3_API_BIND_ADDR:-0.0.0.0:3901}"
GARAGE_S3_REGION="${GARAGE_S3_REGION:-us-east-1}"

GARAGE_WEB_BIND_ADDR="${GARAGE_WEB_BIND_ADDR:-0.0.0.0:3902}"
GARAGE_WEB_ROOT_DOMAIN="${GARAGE_WEB_ROOT_DOMAIN:-.web.garage.local}"
GARAGE_WEB_INDEX="${GARAGE_WEB_INDEX:-index.html}"

GARAGE_ADMIN_API_BIND_ADDR="${GARAGE_ADMIN_API_BIND_ADDR:-0.0.0.0:3903}"

# ---------------------------------------------------------------------------
# 2. Validate required secrets
# ---------------------------------------------------------------------------
if [ -z "${GARAGE_RPC_SECRET}" ]; then
    echo "ERROR: GARAGE_RPC_SECRET is not set."
    echo "Generate one with: openssl rand -hex 32"
    exit 1
fi

# ---------------------------------------------------------------------------
# 3. Generate garage.toml
# ---------------------------------------------------------------------------
generate_config() {
    cat > "${CONFIG}" <<EOF
# Auto-generated by entrypoint.sh — do not edit manually inside the container.

rpc_bind_addr = "${GARAGE_RPC_BIND_ADDR}"
rpc_secret    = "${GARAGE_RPC_SECRET}"

metadata_dir = "${GARAGE_METADATA_DIR}"
data_dir     = "${GARAGE_DATA_DIR}"

# Single-node deployment
replication_factor = 1
consistency_mode   = "consistent"

[s3_api]
api_bind_addr = "${GARAGE_S3_API_BIND_ADDR}"
s3_region     = "${GARAGE_S3_REGION}"

[s3_web]
bind_addr   = "${GARAGE_WEB_BIND_ADDR}"
root_domain = "${GARAGE_WEB_ROOT_DOMAIN}"
index       = "${GARAGE_WEB_INDEX}"

[admin]
api_bind_addr = "${GARAGE_ADMIN_API_BIND_ADDR}"
EOF
    echo "✅ ${CONFIG} generated."
    echo "--- Generated config ---"
    cat "${CONFIG}"
    echo "--- End config ---"
}

# ---------------------------------------------------------------------------
# 4. Initialize cluster (runs once)
# ---------------------------------------------------------------------------
init_cluster() {
    echo ""
    echo "=========================================="
    echo "  Initializing Garage Single-Node Cluster"
    echo "=========================================="
    echo ""

    echo "→ Retrieving node ID..."
    NODE_ID=$(/usr/local/bin/garage -c "${CONFIG}" node id)
    echo "   Node ID: ${NODE_ID}"

    echo "→ Assigning layout (zone=dc1, capacity=1G)..."
    /usr/local/bin/garage -c "${CONFIG}" layout assign "${NODE_ID}" --zone dc1 --capacity 1G

    echo "→ Applying layout..."
    /usr/local/bin/garage -c "${CONFIG}" layout apply --version 1

    echo "→ Cluster status:"
    /usr/local/bin/garage -c "${CONFIG}" status || true

    if [ -n "${GARAGE_INIT_BUCKET}" ]; then
        echo "→ Creating bucket '${GARAGE_INIT_BUCKET}'..."
        /usr/local/bin/garage -c "${CONFIG}" bucket create "${GARAGE_INIT_BUCKET}" || true
    fi

    if [ -n "${GARAGE_INIT_KEY}" ]; then
        echo "→ Creating access key '${GARAGE_INIT_KEY}'..."
        /usr/local/bin/garage -c "${CONFIG}" key create "${GARAGE_INIT_KEY}" || true
    fi

    if [ -n "${GARAGE_INIT_BUCKET}" ] && [ -n "${GARAGE_INIT_KEY}" ]; then
        echo "→ Granting read+write on '${GARAGE_INIT_BUCKET}' to key '${GARAGE_INIT_KEY}'..."
        /usr/local/bin/garage -c "${CONFIG}" bucket allow \
            "${GARAGE_INIT_BUCKET}" --read --write --key "${GARAGE_INIT_KEY}" || true
    fi

    touch "${MARKER}"
    echo ""
    echo "✅ Initialization complete."
    echo ""
}

# ---------------------------------------------------------------------------
# 5. Main
# ---------------------------------------------------------------------------
generate_config
mkdir -p "${GARAGE_METADATA_DIR}" "${GARAGE_DATA_DIR}"

# Detect stale database from a previous failed initialization
if [ ! -f "${MARKER}" ] && [ -d "${GARAGE_METADATA_DIR}/db.lmdb" ]; then
    echo ""
    echo "⚠️  WARNING: Old metadata database found but no init marker."
    echo "    This usually means a previous deployment failed and left stale state."
    echo "    Garage will likely error with 'replication_mode vs replication_factor'."
    echo ""
    echo "    FIX: In Coolify, delete this resource's Persistent Storage, then redeploy."
    echo "    Or SSH into the server and run:  docker volume ls  &&  docker volume rm <garage-volume>"
    echo ""
fi

if [ -f "${MARKER}" ]; then
    echo "Garage already initialized. Starting server..."
    exec /usr/local/bin/garage -c "${CONFIG}" server
else
    echo "First boot detected. Starting server for initialization..."
    /usr/local/bin/garage -c "${CONFIG}" server &
    PID=$!

    echo "Waiting for Garage to be ready..."
    for i in $(seq 1 60); do
        if /usr/local/bin/garage -c "${CONFIG}" status >/dev/null 2>&1; then
            echo "Garage is ready."
            break
        fi
        if ! kill -0 "${PID}" 2>/dev/null; then
            echo "ERROR: Garage server exited unexpectedly during startup."
            exit 1
        fi
        sleep 2
    done

    init_cluster

    echo "Restarting Garage in foreground..."
    kill "${PID}" 2>/dev/null || true
    wait "${PID}" 2>/dev/null || true

    exec /usr/local/bin/garage -c "${CONFIG}" server
fi
